name: Optimize Images

on:
  push:
    paths:
      - 'eos_wallpapers_classic/**'
      - 'eos_wallpapers_community/**'
      - 'scripts/optimize-images.sh'

jobs:
  optimize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install optimization tools
        run: |
            sudo apt-get update
            sudo apt-get install -y jpegoptim cargo
            cargo install oxipng

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Make script executable
        run: chmod +x scripts/optimize-images.sh

      - name: Run optimization script
        run: ./scripts/optimize-images.sh

      - name: Check for changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Optimize images on $(date '+%Y-%m-%d')"
          git push

      - name: Create release archive
        run: |
          tar --exclude='.git' --exclude='scripts' --exclude='README.md' --exclude='community-wallpapers.png' \
              -czf wallpapers_release.tar.gz eos_wallpapers_community eos_wallpapers_classic

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: "Automated Release ${{ github.run_number }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./wallpapers_release.tar.gz
          asset_name: wallpapers_release.tar.gz
          asset_content_type: application/gzip
