name: Create and Upload Release

on:
  workflow_run:
    workflows: ["Optimize"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create release archives
        run: |
          tar --exclude='.git' --exclude='scripts' --exclude='README.md' --exclude='community-wallpapers.png' \
              -czf eos_wallpapers_community_release.tar.gz eos_wallpapers_community
          tar --exclude='.git' --exclude='scripts' --exclude='README.md' --exclude='community-wallpapers.png' \
              -czf eos_wallpapers_classic_release.tar.gz eos_wallpapers_classic

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: "EndeavourOS Community wallpapers ${{ github.run_number }}"
          draft: false
          prerelease: false

      - name: Upload eos-ce-wallpapers_release.tar.gz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./eos_wallpapers_community_release.tar.gz
          asset_name: eos_wallpapers_community_release.tar.gz
          asset_content_type: application/gzip

      - name: Upload eos_wallpapers_classic.tar.gz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./eos_wallpapers_classic_release.tar.gz
          asset_name: eos_wallpapers_classic_release.tar.gz
          asset_content_type: application/gzip
